config/routes.rb
Rails.application.routes.draw do
  resources :financial_products

  resources :contacts

  resources :user_searches

  resources :private_messages
  controller :private_messages do
    get "private_message/sent" => :sent, as: "private_message_sent"
  end
  namespace :broker do
    resources :activities
  end
  namespace :user do
    resources :activities
  end  
  controller :activities do
    get "news" => :index
    
  end

  resources :financial_goal_story_rels
  resources :micro_comments
  resources :financial_testimonies
  resources :financial_stories

  resources :licenses
  
  resources :experiences
  resources :educations
  get 'remove_id/:id' => 'setup_brokers#remove_id', :as => :remove_id
  get 'broker_licenses/:id' => 'setup_brokers#download_broker_license', :as => :download_broker_license
  get 'driver_licenses/:id' => 'setup_brokers#download_driver_license', :as => :download_driver_license
  resources :setup_brokers, path: "registration", as: :setup_brokers

  controller :authentication_out do
    get 'facebook'=> :facebook
    get 'linkedin'=> :linkedin
    get 'googleplus'=> :googleplus
    get 'twitter'=> :twitter
  end
  resources :authentication_in
  controller :authentication_in do
    get 'failure'=>:failure
  end
  get 'auth/:provider/callback', to: 'authentication_in#create'
  get '/auth/failure', :to => 'authentication_in#failure'
  get '/logout', :to => 'user/sessions#destroy', :as => 'logout'

  resources :advance_search
  resources :broker_search  
  resources :backgrounds
  controller :backgrounds do
    get 'add_assoc'=> :add_assoc
    get 'remove_assoc'=> :remove_assoc
    get 'info'=> :info
    get 'direct_to'=> :direct_to

  end
  resources :brokers

  controller :brokers do
    get 'broker/signup'=> :new
    get "broker/home/:id" => :home, as: 'broker_home'
    get "add_license" => :add_license
    get 'crop'=> :crop
  end
 
  namespace :admin do
    resources :product_relations, controller: 'product_fin_category_rels'
    resources :activities
    resources :companies
    resources :products
    resources :broker_requests
    controller :admin_pages do
      get "home" => :index
    end
  end

  namespace :user do
    resources :authenticated
    controller :sessions do
    get 'login'=> :new
    get 'password_prompt'=> :password_prompt
    get 'password_lookup/:id'=> :edit, as:"password_lookup"
    post 'signin'=> :create
    patch 'send_password'=> :update
    delete 'logout'=> :destroy

   end
  end
  namespace :broker do
    controller :sessions do
      get 'login'=> :new
      get 'password_prompt'=> :password_prompt_1, as:"password_prompt"
      get 'password_lookup/:id'=> :password_lookup_2, as: "password_lookup"
      get 'enter_new_password/:id'=> :enter_new_password_3, as: "enter_new_password"
      get 'search'=> :search, as:"password_lookup_search"
      patch 'send_password/:id'=> :update, as: "send_password"
      patch 'reset_password/:id'=> :update, as: "reset_password"
      post "signin"=> :create
      delete "logout"=> :destroy
    end

  end

  resources :goals

  resources :users
  controller :users do
    get 'signup'=> :new
    get 'crop'=> :crop
    get 'user/home/:id'=> :home, as: 'user_home'
  end
  resources :setups
  controller :setups do
    get 'setup/:id'=> :edit, as: 'custom_edit_setup'
  end
  match '/users/remove/:id', to:'users#remove',via:'get', as: 'user_remove'

  match'/admin/remove/:id', to:'users#admin_remove', via:'get', as: 'admin_remove'
  root 'static_pages#home'
  controller :static_pages do
    
    get "about" => :about
    get "home" => :home
    get "faq" => :faq
    get "announcement" => :announcement
    get "broker_background_check" => :broker_background_check
    get "broker_registration_criteria" => :broker_registration_criteria
    get "why_richrly" => :why_richrly
  end
  scope '/legal' do
    controller :legal do
      get "user_agreement" => :user_agreement
      get "privacy_policy" => :privacy_policy
      get "disclaimer" => :disclaimer
      get "copyright_policy" => :copyright_policy
    end
  end
  
  
  resources :spendings
  resources :transaction_imports
  controller :transaction_imports do
    get 'import' => :new
    get 'template' => :template
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def about
  end

  def contact
    @contact=Contact.new
  end
  def why_richrly
  end
  def announcement
  end
  def faq
  end
  def home
  end
  def broker_background_check
  end
  def broker_registration_criteria
  end
end

app/views/static_pages/_form.html.erb
<%= form_for @user do |f| %>
<div class="panel panel-default">
  <div class="panel-body">
    
    <h3>Sign Up Now</h3>
    <div align="left">
      <p>
        <%= f.label "Username" %> <span style="color:red"><i>(case insensitive)</i><%=asterisk_html%></span>
      </p>
      <p>
        <%= f.text_field :username,{:class=>'form-control', :title=>"Please enter username"} %>
      </p>
      <p><%= f.label "Password" %><%=asterisk_html%></p>
      <p><%= f.password_field :password,{:class=>'form-control'} %></p>

      <p><%= f.label "Password Confirmation" %><%=asterisk_html%></p>
      <p><%= f.password_field :password_confirmation,{:class=>'form-control'} %></p>
      
    </div>
    <p><%= f.submit 'Create Account', :class=>"btn btn-primary" %></p>
  </div>
</div>
<%end%>

app/views/static_pages/about.html.erb
<% content_for :title do %>|About<%end%>
<h1>About RichRly</h1><br><br><br>
<div style="text-align:left;">
  <div class="about" style="float:left; width:60%;">
     <p>
      RichRly was founded in 2015 in NYC. As of today, it is a very young startup with a vision to help educating people about financial planning and finding the right financial representatives. Why? We have noticed that general public face the following obstacle in their first financial planning:
    </p>
    <p>
      <b>People have No time, no resources, and no idea.</b>
    </p>
    <p>
      Here we are, with a few clicks of a button this website gives an idea of possible financial strategy and connect them with potential representatives based on their financial need. 
    </p> 
      
  </div>
  <div style="overflow:auto;">
    <%=image_tag "home_picture5.jpg", style: 'width:300px;height:auto;'%>
    <br><i>Image courtesy of pakorn at FreeDigitalPhotos.net</i>
  </div>
  <div style="clear:both;height:20px;"></div>
  <h2>Meet Our Team</h2>
  <div style="float:left;">
    <%=image_tag "antonio_jha.jpeg", size:"250x250"%>
  </div>
  <div class="about" style="overflow:auto;padding-left:25px;vertical-align:top;">
    <h2>Antonio Jha <small>Webmaster</small></h2>

    <p>&nbsp &nbsp &nbsp &nbsp Antonio is the webmaster who developed the company website. Before working at RichRly, Antonio is an independent software developer who has 2+ years of experience with website development in both front-end and back-end. Besides being a software developer, Antonio enjoys site seeing and visiting various restaurant in NYC. Maybe you will see him one day waiting online outside of some delicious food hubs.<p>
  </div>

  <div style="clear:both; height:20px;"></div>
</div>

app/views/static_pages/announcement.html.erb
<h1>Annoucement</h1>

<div class="jumbotron" style="text-align:left;">
  <h1>RichRly Beta launches on October 1!</h1>
  <p> Posted on 9/6/2015</p>
</div>

app/views/static_pages/basic_info.html.erb
Many people do not understand what brokers do

http://www.finra.org/investors/brokers

app/views/static_pages/blog.html.erb
<% content_for :title do %>|Blog<%end%>
<h1>Blog</h1>

app/views/static_pages/broker_background_check.html.erb
<span class="customize-title"><h1>Financial Broker Background Check Guide</h1></span>

<div class="about">

<p>RichRly conducts background check to make sure financial advisors registered on our websites possess valid CRD (Central Registration Deposit) number if they are investment brokers or license number if they are life/health insurance brokers. <b>However, it’s your responsibility to check if an advisor is a registered broker in a good standing with regulators or his/her clients before you entrust your money to him/her. Otherwise, there may be no way for you to recover your money later.</b></p>
<p>Note that the instruction below are divided based on whether you are doing a search for</p> 
  <ol>
    <li>Investment broker (financial representative who possesses series 3, 6, 7, or 65 license) or</li>
    <li>Insurance agent (financial representative who possesses life or health insurance license).</li>
  </ol>
  <h2>To Conduct Background Check on Investment Broker</h2>
  <p>Please refer for complete guide at SEC (U.S Securities and Exchange Commission) <%=link_to "website", "http://www.sec.gov/investor/brokers.htm"%> before you select an investment broker.</p> 
  <p>To ease your search, you can follow these steps:</p>
  <p>
  <b>Step 1:</b> Go to FINRA’s BrokerCheck <%=link_to "website", "http://brokercheck.finra.org/"%>.<br>
  <b>Step 2:</b> Type in your broker’s CRD number or the name of your broker or brokerage firm, and click “Start Search.” <br>
  <b>Step 3:</b> Locate your broker or firm in the search results, and click on his or her name.<br>
  <b>Step 4:</b> You’re done! You should now be able to view your broker’s name, CRD number, employment history, qualifications, disciplinary disclosures, etc.
  </p>

  <h2>To Conduct Background Check on Insurance Agent</h2>
<p>Please refer for complete guide before you select your insurance agent at NAIC (National Association of Insurance Commissioners) <%=link_to "website", "http://www.naic.org/documents/consumer_alert_selecting_agent.htm"%>.</p> 
  
  <p><b>Note:</b> The following instruction only applies for checking background of registered life or health insurance agents in <b>New York</b> State.</p>

  <h3>To check your insurance agent’s license information:</h3><br>
  <p>To ease your search, you can follow these steps:</p>
  <p>
    <b>Step 1:</b> Go to New York State Department of Financial Services <%=link_to "website", "https://myportal.dfs.ny.gov/nylinxext/elsearch.alis"%>. You will probably be asked to enter some numbers or letters to verify that you are a human—this simply helps prevent unauthorized access.<br>
  <b>Step 2:</b> Select LIFE AND/OR ACCIDENT/HEALTH AGENT or LIFE BROKER in Class field,  type in your broker’s license number or the name of your broker, and click “Search.”<br> 
  <b>Step 3:</b> Locate your broker or firm in the search results, and click on his or her name.<br>
  <b>Step 4:</b> You should now be able to view your broker’s name, license number, companies that the broker is appointed with and insurance products that the broker is allowed to sell.<br>
  <b>Step 5:</b> To check if there is any disciplinary action on a broker visit the following website <%=link_to "http://www.dfs.ny.gov/insurance/search_da.htm", "http://www.dfs.ny.gov/insurance/search_da.htm"%>.
  
  </p>
  
  <h3>To check Insurance Company Rating and Stability visit the following website:</h3>
  <ol>
    <li>For company rating and stability - <%=link_to "http://www.dfs.ny.gov/consumer/ratings_stability.htm","http://www.dfs.ny.gov/consumer/ratings_stability.htm"%>. </li>
    <li>For any complaint against an institution - <%=link_to "https://eapps.naic.org/cis/","https://eapps.naic.org/cis/"%>. </li>

  </ol>
</div>

app/views/static_pages/broker_registration_criteria.html.erb
<span class="customize-title"><h1>Broker Registration Criteria</h1></span>

<div class="about">

<h3>RichRly will only approve registration from a financial representative if he/she satisfies all of the following criteria:</h4>
<ol>
  <li>Your driver license ID matches with your broker license identification.</li>
  <li>Your license is registered in the state of <span style="text-decoration: underline;">New York</span>.</li>
<li>The license/CRD number you provided is a valid license number. A valid license should be an active license that has not passed its expiration date. RichRly will only display your license information only if your license check is approved.</li>
  <li>You are in good standing with any licensing or certification bodies of which you are a member.</li>
</ol>
<h3>For your profile to be visible to Members, you must have completed the following:</h4>
<ol>
  <li>Your registration was approved.</li>
  <li>You must submit at least one financial story detailing how you have helped your client in the past and this financial story will be displayed on your profile. Other Members will also be able to view your financial stories freely.</li>
</ol>
</div>

app/views/static_pages/demo.html.erb
<% content_for :title do %>|Demo<%end%>
<h1>Demo</h1>

app/views/static_pages/faq.html.erb
<% content_for :title do%>|Faq <%end%>
<span class="customize-title"><h1>Frequently Asked Questions</h1></span>
<div class="about">
  
  
  <div style="width:50%;float:left;padding:10px;">
    <h3>For Non-Finance Professional Member</h3>
    <br><br>
    <p><b>1. What makes RichRly different from other financial blog/forum?</b></p>
    <p>A: Financial representatives who come to RichRly has to post their personal financial story which details how they helped their customer through a financial vehicle. We believe that learning through personal stories is much more helpful than learning from general financial blogs or articles. For more information about benefit for using RichRly please refer to <%=link_to "Why RichRly?", why_richrly_path%></p>
     <p><b>2. Where do I start if I have no prior experience in financial planning?</b></p>
  <p>A: RichRly has designated simple definitions for each financial vehicle in the financial articles section. Furthermore, beginner can read financial articles to gain understanding on how these financial vehicles are utilized. These are for our members to gain a deeper understanding of various financial planning strategies. </p>
    <p><b> 3. How is RichRly going to secure reliable professionals?</b></p>
    <p>A: RichRly conducts background check on each financial advisor when they register, specifically their ID and license/CRD number. If their background does not satisfy the criteria required by RichRly, their registration would be denied. If you want to know what criteria RichRly uses to select financial representatives, see <%=link_to "here", broker_registration_criteria_path%> for the criteria. We also encourage members to conduct background check on financial advisor themselves; please follow the instruction given <%=link_to "here", broker_background_check_path%>.</p>
    <p><b> 4. I do not live in NY, can I sign up?</b></p>
  <p>A: Yes. RichRly welcomes anyone who resides in the United States to sign up on our website. </p>


  </div>
  <div style="width:50%;overflow:auto;padding:10px;">

    <h3>For Financial Advisor</h3>
    <br><br>
    <p><b>1. How is RichRly going to promote my business?</b></p>
  <p>A: RichRly will display your profile and financial story to its members, and with the profile you have created it allows users to have better understanding with your backgrounds when making selection of professionals. For more information about benefit for using RichRly please refer to <%=link_to "Why RichRly?", why_richrly_path%></p>
    <p><b>2. Do I need to pay commission to RichRly when we close a deal with clients?</b></p>
    <p>A: No. RichRly does not take commission and is not liable for any sale that is promoted through RichRly.</p> 
    <p><b>3. Can I use RichRly to reach out to potential clients?</b></p>
    <p>A: Yes. You are free to use RichRly’s private message to reach out to potential clients. However, RichRly discourages the use of personal email address posted on member’s profile since this often may be mistaken as spam message. If you’re in doubt on what you can do or can’t do, please refer to Section 8- RichRly “Dos” and “Don’ts” of <%=link_to "User Agreement", user_agreement_path%>.</p>
    <p><b>4. I do not live in NY, can I sign up?</b></p>
    <p>A: We currently do not accept broker registration from outside the state of New York. However, we aim to expand our service the entire states.</p>
  </div>

</div>

app/views/static_pages/home.html.erb
<%content_for :title do%>|Home<%end%>


<% content_for :banner do %>
<div class="home_background" style="overflow:auto;">
</div>
<div width="100%" align="center">
  <table width="90%">
    <tr>
      <td width="25%" style="padding-left:20px;">
        <%=render "layouts/logo"%>
      </td>
      <td width="75%"> 
        <h3><b>Get Financial Planning Ideas, Get Connected!</b></h3>
      </td>
    </tr>
  </table>
</div>
<%end%>
<% content_for :left do %>
<div style="width:100%;">
    <%@user=User.new%>
    <%=render 'form'%>
</div>
<%end%>

<div style="width:100%; text-align:left; padding:10px;">
  <h4>What Does RichRly Offer?</h4>
  <div style="font-size:1.1em;"> 
  There is a need for professionals who do not know how to start with their first financial plan. RichRly provides an integrated platform present financial planning information and connecting financial representatives with general public. The website provides easy access to view many financial planning strategies posted by financial professionals free of charge. It’s a great tool if you want to start learning about financial planning or want to expand your financial planning knowledge.
   
  </div>
  <table width="100%">
    <tr>
      <td width="33%" style="vertical-align:top; text-align:center;">
        <h3><b>Get Ideas</b></h2>
        <%=image_tag "home_picture3.jpg", size: "200x180"%><br>   
        <i>Image courtesy of ratch0013 at FreeDigitalPhotos.net</i>
      </td>
      <td width="33%" style="vertical-align:top; text-align:center;">
        <h3><b>Get Connected</b></h2>
        <%=image_tag "home_picture9.jpg", size: "200x150"%><br>
        <i>Image courtesy of bplanet at FreeDigitalPhotos.net</i>
      </td>
      <td width="33%" style="vertical-align:top; text-align:center;">
        <h3><b>Get Educated</b></h2>
        <%=image_tag "home_picture1.jpg", size: "150x150"%><br>   
        <i>Image courtesy of Ppiboon at FreeDigitalPhotos.net</i>
      </td>
    </tr>
    <tr>
      <td style="padding:10px;vertical-align:top;">
        <div style="font-size:1.3em;">   
    You can gather ideas of financial strategy based on your financial interests and vehicles.
        </div>
      </td>
      <td style="padding:10px;vertical-align:top;">
        <div style="font-size:1.3em;">
  You can connect with financial representatives on RichRly and view their background. 
        </div>
      </td>
      <td style="padding:10px;vertical-align:top;">
        <div style="font-size:1.3em;">
        You can learn about various financial vehicles and its uses. 
        </div>
      </td>
    </tr>
  </table>  

</div>

<div style="float:right; vertical-align:top;">
  
  
  
</div>

app/views/static_pages/why_richrly.html.erb
<span class="customize-title"><h1>Why RichRly?</h1></span>
<div class="about">
  <div style="width:50%;float:left;padding:10px;">
    <h3><b>For Non-Finance Professional Member</b></h3>
    <br><br>
    <p>RichRly offers a platform for non-financial professional to learn about various financial planning strategies through the following ways:</p>
    <ol>
      <li>Learn various financial vehicles and its uses through personal financial stories posted by financial advisors. Personal financial stories detail how a financial advisor helps his/her customer with a particular financial vehicle.</li>
      <li>Learn general financial planning strategy through the blog RichRly provides. Each week, RichRly researches about a specific financial planning topic and post an article to explain various strategies related to the topic.</li>
      <li>Organize your financial planning strategies under your personal financial goals. You can create any financial goal and save the posted financial stories under any particular goal.</li>
      <li>Through profile and posted financial stories, conduct background check on financial advisors to see if any person is fit to be your personal advisor.</li>
      <li>Interact with various financial advisors without direct contact or any commitment.</li>
    </ol>

  </div>
  <div style="width:50%;overflow:auto;padding:10px;"> 
    <h3><b>For Financial Advisor</b></h3>
    <br><br>
    <p>RichRly offers financial advisors a platform to promote their business through the following ways:</p>
    <ol>
      <li>Advertisement- RichRly offers financial advisors an easy way to advertise for themselves and build credibility with their potential clients. Members can view financial advisors’ profile and learn about their background and experience.</li>
      <li>Showcase your success story- when you post a financial article on RichRly, members can vote up your story if they find it to be helpful. Financial article with the most vote ups will be ranked first. If many people find your article to be helpful, they may contact you and become your client. </li>
      <li>You can use RichRly to conduct market research. You can gather information about member’s financial interest and other profile information to better understand need of your potential clients.</li>
    </ol>
  </div>
</div>