config/routes.rb
Rails.application.routes.draw do
  resources :financial_products

  resources :contacts

  resources :user_searches

  resources :private_messages
  controller :private_messages do
    get "private_message/sent" => :sent, as: "private_message_sent"
  end
  namespace :broker do
    resources :activities
  end
  namespace :user do
    resources :activities
  end  
  controller :activities do
    get "news" => :index
    
  end

  resources :financial_goal_story_rels
  resources :micro_comments
  resources :financial_testimonies
  resources :financial_stories

  resources :licenses
  
  resources :experiences
  resources :educations
  get 'remove_id/:id' => 'setup_brokers#remove_id', :as => :remove_id
  get 'broker_licenses/:id' => 'setup_brokers#download_broker_license', :as => :download_broker_license
  get 'driver_licenses/:id' => 'setup_brokers#download_driver_license', :as => :download_driver_license
  resources :setup_brokers, path: "registration", as: :setup_brokers

  controller :authentication_out do
    get 'facebook'=> :facebook
    get 'linkedin'=> :linkedin
    get 'googleplus'=> :googleplus
    get 'twitter'=> :twitter
  end
  resources :authentication_in
  controller :authentication_in do
    get 'failure'=>:failure
  end
  get 'auth/:provider/callback', to: 'authentication_in#create'
  get '/auth/failure', :to => 'authentication_in#failure'
  get '/logout', :to => 'user/sessions#destroy', :as => 'logout'

  resources :advance_search
  resources :broker_search  
  resources :backgrounds
  controller :backgrounds do
    get 'add_assoc'=> :add_assoc
    get 'remove_assoc'=> :remove_assoc
    get 'info'=> :info
    get 'direct_to'=> :direct_to

  end
  resources :brokers

  controller :brokers do
    get 'broker/signup'=> :new
    get "broker/home/:id" => :home, as: 'broker_home'
    get "add_license" => :add_license
    get 'crop'=> :crop
  end
 
  namespace :admin do
    resources :product_relations, controller: 'product_fin_category_rels'
    resources :activities
    resources :companies
    resources :products
    resources :broker_requests
    controller :admin_pages do
      get "home" => :index
    end
  end

  namespace :user do
    resources :authenticated
    controller :sessions do
    get 'login'=> :new
    get 'password_prompt'=> :password_prompt
    get 'password_lookup/:id'=> :edit, as:"password_lookup"
    post 'signin'=> :create
    patch 'send_password'=> :update
    delete 'logout'=> :destroy

   end
  end
  namespace :broker do
    controller :sessions do
      get 'login'=> :new
      get 'password_prompt'=> :password_prompt_1, as:"password_prompt"
      get 'password_lookup/:id'=> :password_lookup_2, as: "password_lookup"
      get 'enter_new_password/:id'=> :enter_new_password_3, as: "enter_new_password"
      get 'search'=> :search, as:"password_lookup_search"
      patch 'send_password/:id'=> :update, as: "send_password"
      patch 'reset_password/:id'=> :update, as: "reset_password"
      post "signin"=> :create
      delete "logout"=> :destroy
    end

  end

  resources :goals

  resources :users
  controller :users do
    get 'signup'=> :new
    get 'crop'=> :crop
    get 'user/home/:id'=> :home, as: 'user_home'
  end
  resources :setups
  controller :setups do
    get 'setup/:id'=> :edit, as: 'custom_edit_setup'
  end
  match '/users/remove/:id', to:'users#remove',via:'get', as: 'user_remove'

  match'/admin/remove/:id', to:'users#admin_remove', via:'get', as: 'admin_remove'
  root 'static_pages#home'
  controller :static_pages do
    
    get "about" => :about
    get "home" => :home
    get "faq" => :faq
    get "announcement" => :announcement
    get "broker_background_check" => :broker_background_check
    get "broker_registration_criteria" => :broker_registration_criteria
    get "why_richrly" => :why_richrly
  end
  scope '/legal' do
    controller :legal do
      get "user_agreement" => :user_agreement
      get "privacy_policy" => :privacy_policy
      get "disclaimer" => :disclaimer
      get "copyright_policy" => :copyright_policy
    end
  end
  
  
  resources :spendings
  resources :transaction_imports
  controller :transaction_imports do
    get 'import' => :new
    get 'template' => :template
  end

end

app/views/shared/_error_message.html.erb
<% if object && object.errors.any? %>
  <div class="alert alert-danger error-message" style="width:100%;">
    <% if object.errors.count >1%>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    <%else%>
    <%=object.errors.full_messages.first%>
      <%if object.addition_error_msg%>
        <%=object.addition_error_msg%>
      <%end%>
    <%end%>
  </div>
<% end %>

app/views/shared/_home_goal_intro.html.erb
<%interest=interest.downcase %>
<h3><%=interest.titleize%></h3>
<table>
  <tr>
    <td width="40%">
      <%if interest=="protection"%>
      <%=image_tag("protection.jpg", class:"goal_pic")%>
      <%elsif interest=="debt management"%>
      <%=image_tag("debt_management-2.jpg", class:"goal_pic")%>
      <%elsif interest=="retirement"%>
      <%=image_tag("retirement.jpg", class:"goal_pic")%>
      <%elsif interest=="investment"%>
      <%=image_tag("investment.jpg", class:"goal_pic")%>
      <%elsif interest=="education fund"%>
      <%=image_tag("education_fund.jpg", class:"goal_pic")%>
      <%elsif interest=="estate planning"%>
      <%=image_tag("estate_planning.jpg", class:"goal_pic")%>
      <%elsif interest=="tax saving"%>
      <%=image_tag("tax_saving.jpg", class:"goal_pic")%>
      <%end%>
    </td>
    <td width="60%">
      <%if interest=="protection"%>
      <div style="float:left;">
        Protection is important if you have family members who depends on your income. In case you are unavilable to provide earning to your family due to illness or accident, protection plan helps to offset the loss income to pay for your monthly expenses.
      </div>
      <%elsif interest=="debt management"%>
      <div style="float:left;">
        Debt Management is important if you have family members who depends on your income.
      </div>
      <%elsif interest=="retirement"%>
      <div style="float:left;">
        Retirement Plan is divided into Employer-Sponsored Plans or Individual Plans. Retirement Plan provides a way for individual to save money and let it grow tax-deferred.
      </div>
      <%elsif interest=="investment"%>
      <div style="float:left;">
        Investment involves any method for individuals or businesses to grow their money through interest. Investment vehicles can have high interest rate but interest earned through investment is taxed as income.
      </div>
      <%elsif interest=="education fund"%>
      <div style="float:left;">
        Education Plan has tax-deferral feature similar to retirement plan and provides a way for you to save your earning which will later be used for your children's education.
      </div>
      <%elsif interest=="estate planning"%>
      <div style="float:left;">
        For large estate above a certain amount, estate tax can become significant. There are some vehicles that can be used to pass on estate to avoid estate tax.
      </div>
      <%elsif interest=="tax reduction"%>
      <div style="float:left;">
        Tax Saving is important if you have family members who depends on your income.
      </div>
      <%end%>

      <p>Below are the various types of vehicle in this category:</p>
      <ol>
        <%products.each do |product|%>     
        <li><%=content_tag(:a,product.name,href:"##{product.name}")%></li>
        <%end%>
      </ol>        
    </td>
  </tr>
</table>
    

app/views/shared/_home_goals_with_stories.html.erb
<%vehicle_type=Order::FINANCIAL_CATEGORIES_HASH.key(interest.titleize)%>
  <%products=Product.where(vehicle_type:vehicle_type)%>
  <%=render partial:"shared/home_goal_intro", locals:{interest:interest, products:products}%>
  <nav>
  <ul class="pager">
    <li role="presentation"><%=link_to "Financial Story","#", id:"financial_stories"%></li>
    <li role="presentation"><%=link_to "Financial Testimony","#", id: "financial_testimonies"%></li>
  </ul>
  </nav>
    <div class="panel panel-default">
      <div class="panel-body" align="left">
        <table width="100%" style="text-align:center;">
          <%size=products.size%>
          <%products.each_with_index do |product,index|%>
            <%if index%2==0 && (index+1<size)%>
            <tr>
              <td width="50%" class="panel panel-primary" style="margin:5px; vertical-align:text-top;">
                <h3>
                  <span class="label label-primary vehicle-heading">
             
                    <%=content_tag(:a,product.name.titleize,name:"#{product.name}", title:product.description)%>
                  </span>
                </h3>
                <div class="panel-body home_display" align="left">

                  <%=render partial:"shared/home_stories", locals:{product:product, interest:interest}%>
                  <%=render partial:"shared/home_testimonies", locals:{product:product, interest:interest}%>
                </div>
              </td>
            <%elsif index%2==1%>
              <td width="50%" class="panel panel-primary" style="margin:5px; vertical-align:text-top;">
                <h3>
                  <span class="label label-primary vehicle-heading">
                    <%=content_tag(:a,product.name.titleize,name:"#{product.name}", title:product.description)%>
                  </span>
                </h3>
                <div class="panel-body" align="left" width="100%">
               
                  <%=render partial:"shared/home_stories", locals:{product:product, interest:interest}%>
                  <%=render partial:"shared/home_testimonies", locals:{product:product, interest:interest}%>
                </div>
              </td>
            </tr>
            <%elsif index%2==0 && (index+1==size)%>
            <tr>
              <td width="50%" class="panel panel-primary" style="margin:5px; vertical-align:text-top;">
                <h3>
                  <span class="label label-primary vehicle-heading">
                    <%=content_tag(:a,product.name.titleize,name:"#{product.name}", title:product.description)%>
                  </span>
                </h3>
                <div class="panel-body" align="left">
              
                  <%=render partial:"shared/home_stories", locals:{product:product, interest:interest}%>
                  <%=render partial:"shared/home_testimonies", locals:{product:product, interest:interest}%>
                </div>
              </td>
              <td width="50%"></td>
            </tr>
            <%end%>
          <%end%>
        </table>
      </div>
    </div>

app/views/shared/_home_stories.html.erb
<div class="financial_stories">
  <%story_count=product.financial_stories.count%>
  <div style="float:left;padding:10px;">
    <b><span style="font-size:1.1em;">Top Financial Story</span></b>
  </div>
  <div style="overflow:auto;text-align:right;padding:10px;">
    <%=link_to "View All #{pluralize(story_count,"Story")}",financial_stories_url(product_id:product.id,interest:interest) %>
  </div>
  <div width="100%" align="left">
    <%financial_stories=product.financial_stories.order(votes: :desc).first(5)%>  
    <%if story_count >0%>
      <table width="100%">    
        <%financial_stories.each do |story|%>
        <tr>
          <td width="30%" style="vertical-align:top;">
            <div style="font-size:1.2em;">
             <span class="label label-success">Upvotes:<%=story.votes%></span>
            </div><br>
            <%=link_to story.broker do %>
            <%=smart_image(story.broker,4)%>
            <%end%>
          </td>
          <td width="70%">    
            <div class="panel panel-default">
              <div class="panel-heading clearfix">           
                <h4><%=link_to story.title, story%></h4>
              </div>
              <div class="panel-body" style="vertical-align:top;">
                Posted by <%=link_to full_name(story.broker), story.broker%><br>
                Posted on <%=story.created_at.strftime("%b,%y at %l:%M %P")%><br> 
              </div>
            </div>
          </td>
        </tr>
        <%end%>
      </table>        
    <%else%>
       None. 
    <%end%>
  </div>
</div>

app/views/shared/_home_testimonies.html.erb
<div class="financial_testimonies" style="display:none;">
  <%testimony_count=product.financial_testimonies.count%>
  <div style="float:left;padding:10px;">
    <b><span style="font-size:1.1em;">Top Financial Testimony</span></b>
  </div>
  <div style="overflow:auto;text-align:right;padding:10px;">
    <%=link_to "View All #{pluralize(testimony_count,"Testimony")}",financial_testimonies_url(product_id:product.id,interest:interest) %>
  </div>
  <div width="100%" align="left">
    <%if testimony_count >0%>
      <%financial_testimonies=product.financial_testimonies.order(votes: :desc).first(5)%>  
      <table width="100%">
        <%financial_testimonies.each do |testimony|%>
        <tr>
          <td width="30%" style="vertical-align:top;">
            <div style="font-size:1.2em;">
             <span class="label label-success">Upvotes:<%=testimony.votes%></span>
            </div><br>
            <%=link_to testimony.user do %>
            <%=smart_image(testimony.user,4)%>
            <%end%>
          </td>
          <td width="70%">    
            <div class="panel panel-default">
              <div class="panel-heading clearfix">           
                <h4><%=link_to testimony.title, testimony%></h4>
              </div>
              <div class="panel-body" style="vertical-align:top;">

                Posted by <%=link_to full_name(testimony.user), testimony.user%><br>
                Posted on <%=testimony.created_at.strftime("%b,%y at %l:%M %P")%><br> 
              </div>
            </div>
          </td>
        </tr>
        <%end%>
      </table>
    <%else%>
      None.
    <%end%>
  </div>
</div>

app/views/shared/home.html.erb
<div width=50% style="float:left;">
  <% if user_logged_in?%>
  <div style="float:left;width:110px;"><%=smart_image(@user,1)%></div>
  <div style="overflow:auto;" align="left"><h3><%=full_name(@user)%></h3></div>
  <% elsif broker_logged_in?%>
  <div style="float:left;width:110px;"><%=smart_image(@broker,1)%></div>
  <div style="overflow:auto;" align="left"><h3><%=full_name(@broker)%></h3></div>  
  <%end%>
</div>
<div style="overflow:auto; text-align:left; font-size:1em;padding:10px;">
  <p><i>Richrly.com makes no representations, warranties, or assurances as to the accuracy, currency or completeness of the content contain on this website or any sites linked to this site. See complete disclaimer policy <%=link_to "here", disclaimer_path%>.</i></p>
</div>
<div style="clear:both;"></div>
<div align="left">
  <ul class="nav nav-pills">
    <%Order::FINANCIAL_CATEGORIES_HASH.values.each do |interest|%>
      <% if user_logged_in?%>
        <%url=user_home_url(interest:interest)%>  
      <%elsif broker_logged_in?%>
        <%url=broker_home_url(interest:interest)%>  
      <%end%>
      <%if interest==@interest.titleize%>
      <li role="presentation" class="active"><%=link_to "#{interest.titleize}",url %></li>
      <%else%>
      <li role="presentation"><%=link_to "#{interest.titleize}",url %></li>
      <%end%>
    <%end%>
  </ul>

  <%=render partial:"shared/home_goals_with_stories", locals:{interest:@interest}%>
</div>