config/routes.rb
Rails.application.routes.draw do
  resources :financial_products

  resources :contacts

  resources :user_searches

  resources :private_messages
  controller :private_messages do
    get "private_message/sent" => :sent, as: "private_message_sent"
  end
  namespace :broker do
    resources :activities
  end
  namespace :user do
    resources :activities
  end  
  controller :activities do
    get "news" => :index
    
  end

  resources :financial_goal_story_rels
  resources :micro_comments
  resources :financial_testimonies
  resources :financial_stories

  resources :licenses
  
  resources :experiences
  resources :educations
  get 'remove_id/:id' => 'setup_brokers#remove_id', :as => :remove_id
  get 'broker_licenses/:id' => 'setup_brokers#download_broker_license', :as => :download_broker_license
  get 'driver_licenses/:id' => 'setup_brokers#download_driver_license', :as => :download_driver_license
  resources :setup_brokers, path: "registration", as: :setup_brokers

  controller :authentication_out do
    get 'facebook'=> :facebook
    get 'linkedin'=> :linkedin
    get 'googleplus'=> :googleplus
    get 'twitter'=> :twitter
  end
  resources :authentication_in
  controller :authentication_in do
    get 'failure'=>:failure
  end
  get 'auth/:provider/callback', to: 'authentication_in#create'
  get '/auth/failure', :to => 'authentication_in#failure'
  get '/logout', :to => 'user/sessions#destroy', :as => 'logout'

  resources :advance_search
  resources :broker_search  
  resources :backgrounds
  controller :backgrounds do
    get 'add_assoc'=> :add_assoc
    get 'remove_assoc'=> :remove_assoc
    get 'info'=> :info
    get 'direct_to'=> :direct_to

  end
  resources :brokers

  controller :brokers do
    get 'broker/signup'=> :new
    get "broker/home/:id" => :home, as: 'broker_home'
    get "add_license" => :add_license
    get 'crop'=> :crop
  end
 
  namespace :admin do
    resources :product_relations, controller: 'product_fin_category_rels'
    resources :activities
    resources :companies
    resources :products
    resources :broker_requests
    controller :admin_pages do
      get "home" => :index
    end
  end

  namespace :user do
    resources :authenticated
    controller :sessions do
    get 'login'=> :new
    get 'password_prompt'=> :password_prompt
    get 'password_lookup/:id'=> :edit, as:"password_lookup"
    post 'signin'=> :create
    patch 'send_password'=> :update
    delete 'logout'=> :destroy

   end
  end
  namespace :broker do
    controller :sessions do
      get 'login'=> :new
      get 'password_prompt'=> :password_prompt_1, as:"password_prompt"
      get 'password_lookup/:id'=> :password_lookup_2, as: "password_lookup"
      get 'enter_new_password/:id'=> :enter_new_password_3, as: "enter_new_password"
      get 'search'=> :search, as:"password_lookup_search"
      patch 'send_password/:id'=> :update, as: "send_password"
      patch 'reset_password/:id'=> :update, as: "reset_password"
      post "signin"=> :create
      delete "logout"=> :destroy
    end

  end

  resources :goals

  resources :users
  controller :users do
    get 'signup'=> :new
    get 'crop'=> :crop
    get 'user/home/:id'=> :home, as: 'user_home'
  end
  resources :setups
  controller :setups do
    get 'setup/:id'=> :edit, as: 'custom_edit_setup'
  end
  match '/users/remove/:id', to:'users#remove',via:'get', as: 'user_remove'

  match'/admin/remove/:id', to:'users#admin_remove', via:'get', as: 'admin_remove'
  root 'static_pages#home'
  controller :static_pages do
    
    get "about" => :about
    get "home" => :home
    get "faq" => :faq
    get "announcement" => :announcement
    get "broker_background_check" => :broker_background_check
    get "broker_registration_criteria" => :broker_registration_criteria
    get "why_richrly" => :why_richrly
  end
  scope '/legal' do
    controller :legal do
      get "user_agreement" => :user_agreement
      get "privacy_policy" => :privacy_policy
      get "disclaimer" => :disclaimer
      get "copyright_policy" => :copyright_policy
    end
  end
  
  
  resources :spendings
  resources :transaction_imports
  controller :transaction_imports do
    get 'import' => :new
    get 'template' => :template
  end

end

app/models/transaction_import.rb
class TransactionImport < ActiveRecord::Base
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  attr_accessor :file
  def save(user_id)
    if imported_transactions.map(&:valid?).all?
      imported_transactions.each do |t|
        t.user_id=user_id
        t.save
      end
      true
    else
      imported_transactions.each_with_index do |transaction,index|
        transaction.errors.full_messages.each do |message|
          errors.add :base, "Row #{index+2}:#{message}"
        end
      end
      false
    end
  end
  def imported_transactions
    @imported_transactions||=load_imported_transactions
  end
  def load_imported_transactions
    
    spreadsheet=open_spreadsheet
    header=spreadsheet.row(1)
    (2..spreadsheet.last_row).map do |i|
      row=Hash[[header, spreadsheet.row(i)].transpose]
      transaction=Spending.find_by_id(row["id"])||Spending.new
      transaction.attributes=row.to_hash.slice(*accessible_attributes)
     # errors.add :base, "category is #{transaction.category}"  
      transaction
    end
  end
  def open_spreadsheet
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
  def accessible_attributes
    %w[description amount category transaction_date]
  end
end

app/controllers/transaction_imports_controller.rb
class TransactionImportsController < ApplicationController
  def new
    @import_params=%w(id description transaction_date amount category )
    @transaction_import=TransactionImport.new
  end
  def create
    @import_params=%w(id description transaction_date amount category )
    @transaction_import=TransactionImport.new(transaction_import_params)
    if @transaction_import.save(session[:user_id])
      redirect_to spendings_url, notice: "Imported products successfully."
    else
      render :new
    end
  end
  def template
    respond_to do |format|
      format.xls
    end
  end
  def transaction_import_params
    params.require(:transaction_import).permit(:file)
  end  
end

app/helpers/transaction_imports_helper.rb
module TransactionImportsHelper
end

app/views/transaction_imports/new.html.erb
<h1>Import Transaction</h1>

<div align="left">
<h4>Please read the following before importing your records.</h4>
<p> Each row uploaded from the excel file will create a new transaction record in the system. If there are rows that are repeated, it will also be created. If the same file is uploaded multiple times, same row will be created multiple times.</p>
  <p> The file has four columns: <strong>Transaction Date, Description, Amount, Category </strong></p> 
<p> Header <strong>Transaction Date, Description, Amount, Category</strong> has to be provided in the first row of the excel file.</p>
  <p> Below is the data format for each field:</p>
<ul>
	<%Spending.columns.each do |column|%>
		<%if @import_params.include?column.name%>	
			<li><strong><%=column.name%></strong>-
				<%=column.type.to_s.titleize%> type
			</li>
		<%end%>
	<%end%>		
</ul>
  
  <p> Category should be entered in integer. Below is the category type correspond to each integer:</p>
<ul>
  <li><strong>Food Expense</strong> -1</li>
  <li><strong>Finance Expense</strong> -2</li>
  <li><strong>Shopping Expense</strong> -3</li>
  <li><strong>Transportation Expense</strong> -4</li>
  <li><strong>Entertainment Expense</strong> -5</li>
  <li><strong>Other Expense</strong> -6</li>
</ul>
<p> For detail instruction please visit <%=link_to 'here', faq_path%>.</p>
  <p> For template please <%=link_to "Click Here",template_path(format:'xls')%></p>
<%= form_for @transaction_import do |f|%>
	<% if @transaction_import.errors.any?%>
		<div id="error_explanation">
			<h2><%=pluralize(@transaction_import.errors.count, "error")%> prohibited this import from completing:</h2>
			<ul>
				<%@transaction_import.errors.full_messages.each do |msg|%>
				<li><%=msg%></li>
		 		<%end%>
			</ul>
		</div>
	<%end%>
	<div class="field">
		<%=f.file_field :file%>
	</div>
	<div><%=f.submit "Import"%></div>
<%end%>

</div>

app/views/transaction_imports/template.xls.erb
<?xml version="1.0"?>

<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="11" ss:Color="#000000"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="s62">
   <NumberFormat ss:Format="Short Date"/>
  </Style>
 </Styles>
 <Worksheet ss:Name="spendings">
  <Table>
   <Row>
    <Cell><Data ss:Type="String">Transaction Date</Data></Cell>
    <Cell><Data ss:Type="String">Description</Data></Cell>
    <Cell><Data ss:Type="String">Amount</Data></Cell>
    <Cell><Data ss:Type="String">Category</Data></Cell>
   </Row>
   
  </Table>
 </Worksheet>
</Workbook>