config/routes.rb
Rails.application.routes.draw do
  resources :financial_products

  resources :contacts

  resources :user_searches

  resources :private_messages
  controller :private_messages do
    get "private_message/sent" => :sent, as: "private_message_sent"
  end
  namespace :broker do
    resources :activities
  end
  namespace :user do
    resources :activities
  end  
  controller :activities do
    get "news" => :index
    
  end

  resources :financial_goal_story_rels
  resources :micro_comments
  resources :financial_testimonies
  resources :financial_stories

  resources :licenses
  
  resources :experiences
  resources :educations
  get 'remove_id/:id' => 'setup_brokers#remove_id', :as => :remove_id
  get 'broker_licenses/:id' => 'setup_brokers#download_broker_license', :as => :download_broker_license
  get 'driver_licenses/:id' => 'setup_brokers#download_driver_license', :as => :download_driver_license
  resources :setup_brokers, path: "registration", as: :setup_brokers

  controller :authentication_out do
    get 'facebook'=> :facebook
    get 'linkedin'=> :linkedin
    get 'googleplus'=> :googleplus
    get 'twitter'=> :twitter
  end
  resources :authentication_in
  controller :authentication_in do
    get 'failure'=>:failure
  end
  get 'auth/:provider/callback', to: 'authentication_in#create'
  get '/auth/failure', :to => 'authentication_in#failure'
  get '/logout', :to => 'user/sessions#destroy', :as => 'logout'

  resources :advance_search
  resources :broker_search  
  resources :backgrounds
  controller :backgrounds do
    get 'add_assoc'=> :add_assoc
    get 'remove_assoc'=> :remove_assoc
    get 'info'=> :info
    get 'direct_to'=> :direct_to

  end
  resources :brokers

  controller :brokers do
    get 'broker/signup'=> :new
    get "broker/home/:id" => :home, as: 'broker_home'
    get "add_license" => :add_license
    get 'crop'=> :crop
  end
 
  namespace :admin do
    resources :product_relations, controller: 'product_fin_category_rels'
    resources :activities
    resources :companies
    resources :products
    resources :broker_requests
    controller :admin_pages do
      get "home" => :index
    end
  end

  namespace :user do
    resources :authenticated
    controller :sessions do
    get 'login'=> :new
    get 'password_prompt'=> :password_prompt
    get 'password_lookup/:id'=> :edit, as:"password_lookup"
    post 'signin'=> :create
    patch 'send_password'=> :update
    delete 'logout'=> :destroy

   end
  end
  namespace :broker do
    controller :sessions do
      get 'login'=> :new
      get 'password_prompt'=> :password_prompt_1, as:"password_prompt"
      get 'password_lookup/:id'=> :password_lookup_2, as: "password_lookup"
      get 'enter_new_password/:id'=> :enter_new_password_3, as: "enter_new_password"
      get 'search'=> :search, as:"password_lookup_search"
      patch 'send_password/:id'=> :update, as: "send_password"
      patch 'reset_password/:id'=> :update, as: "reset_password"
      post "signin"=> :create
      delete "logout"=> :destroy
    end

  end

  resources :goals

  resources :users
  controller :users do
    get 'signup'=> :new
    get 'crop'=> :crop
    get 'user/home/:id'=> :home, as: 'user_home'
  end
  resources :setups
  controller :setups do
    get 'setup/:id'=> :edit, as: 'custom_edit_setup'
  end
  match '/users/remove/:id', to:'users#remove',via:'get', as: 'user_remove'

  match'/admin/remove/:id', to:'users#admin_remove', via:'get', as: 'admin_remove'
  root 'static_pages#home'
  controller :static_pages do
    
    get "about" => :about
    get "home" => :home
    get "faq" => :faq
    get "announcement" => :announcement
    get "broker_background_check" => :broker_background_check
    get "broker_registration_criteria" => :broker_registration_criteria
    get "why_richrly" => :why_richrly
  end
  scope '/legal' do
    controller :legal do
      get "user_agreement" => :user_agreement
      get "privacy_policy" => :privacy_policy
      get "disclaimer" => :disclaimer
      get "copyright_policy" => :copyright_policy
    end
  end
  
  
  resources :spendings
  resources :transaction_imports
  controller :transaction_imports do
    get 'import' => :new
    get 'template' => :template
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :financial_products, dependent: :destroy
  has_many :products, through: :financial_products
end

app/controllers/setup_brokers_controller.rb
class SetupBrokersController < ApplicationController
  before_action :set_broker, only:[:edit,:update]
  before_action :authorize_broker, only:[:edit]
  before_action :redirect_if_registered, only:[:edit]

  def edit
    if @broker.step=="license_info_4"
      @broker.add_or_remove_license
      @licenses=@broker.licenses
    elsif @broker.step=="financial_story_7"
      unless @broker.financial_stories.first
        @financial_story=@broker.financial_stories.build
      end
    end

  end

  def update   
  #  raise "error"
    if params[:back]
      @broker.prev_step
      @broker.save
      redirect_to edit_setup_broker_path(@broker)
    else   
      if (@broker.current_field=="basic_info_1")
        if params[:send_validation]
          @broker.send_email_validation_bool=true
          @validate_email_error=true
        elsif params[:validate_email]
          @broker.validate_email_bool=true 
        else
          @broker.basic_info_bool=true
        end
        #set prev_email for validating email purpose
        @broker.prev_email=@broker.email
      elsif @broker.current_field=="id_2"
        @broker.id_image_bool=true
      elsif (@broker.current_field=="license_3")
        @broker.licensetype_bool=true
      elsif (@broker.current_field=="license_info_4")
        @broker.licenses_upload_bool=true
      elsif (@broker.current_field=="vehicle_5")
        @broker.products_bool=true
      elsif (@broker.current_field=="term_of_use_8")
        @broker.term_of_use_bool=true
      end
      if params[:upload_license]
         @setup_broker=@broker.setup_broker
         if @setup_broker.update(license_params)
           redirect_to edit_setup_broker_path(@broker)
          else
           render "setup_brokers/edit"
          end
      elsif params[:validate_email]
        if @broker.confirm_email?(params[:broker][:validation_code])        
          redirect_to edit_setup_broker_path(@broker)
        else
          render "edit"
        end
      else       
        if params[:signup_provider_bool] =="true" 
          unless params[:send_validation]
            @broker.signup_provider_bool=true
          end
        end
        
        if @broker.update(broker_params)
          if params[:send_validation] 
            if @broker.evaluate_and_reset_email_authen(@broker.prev_email)           
              @broker.send_email_confirmation
              notice="Validation code has been sent to your email."
            end
          elsif params[:submit]
            @broker.set_assoc_experience
            @broker.update_attribute(:setup_completed?, true)
            @broker.broker_requests.create(request_type:"create account",complement:false)
            @broker.licenses.each do |l|
              @broker.broker_requests.create(request_type:"create license", license_id:l.id,complement:true)
            end
          else
            unless params[:upload_id]
              @broker.next_step
              @broker.save
            end
          end
          unless @broker.setup_completed?       
            redirect_to edit_setup_broker_path(@broker), notice:notice         
          else
            redirect_to broker_path(@broker), notice:"Your registration has been submitted and is being reviewed."
          end
        else
          if params[:next_from_pg4]
            @broker.add_or_remove_license
            @licenses=@broker.licenses
          end
          render "edit"
        end
      end
    end 
  end
  def download_driver_license
    @broker=Broker.find(params[:id])
    data = open(@broker.id_image.url) 
    send_data data.read, filename: @broker.id_image.file.filename, type: "application/#{@broker.id_image.file.extension}", disposition: 'inline', stream: 'true', buffer_size: '4096'
  end
  def download_broker_license
    @license= License.find(params[:id])
    data = open(@license.license_image.url) 
    send_data data.read, filename: @license.license_image.file.filename, type: "application/#{@license.license_image.file.extension}", disposition: 'inline', stream: 'true', buffer_size: '4096'
  end
  def remove_id
    @broker=Broker.find(params[:id])
    @broker.remove_id_image!
    @broker.save
    redirect_to edit_setup_broker_url(@broker)
  end
  private
  def authorize_broker
    @broker=Broker.find(params[:id])
    unless session[:broker_id]==@broker.id
      flash[:danger]="Unauthorized access!" 
      redirect_to broker_login_path
    end
  end
  def redirect_if_registered
    if (@broker.setup_completed? == true)
      redirect_to @broker, notice: "Your registration has been submitted. Please wait for it to be processed."
    end
  end
  def set_broker
    if params[:setup_broker] && params[:setup_broker][:broker_id]
      @broker=Broker.find(params[:setup_broker][:broker_id])
    else
      @broker=Broker.find(params[:id])
    end
  end
  def broker_params
    params.require(:broker).permit(:first_name, :last_name, :id_image, :company_name,:company_location, :email, :title,:username,:password,:password_confirmation,{:license_type => []},{:product_ids => []}, :skills, :ad_statement, :check_term_of_use, financial_stories_attributes:[:id, :product_id,:financial_category,:description, :title])
  end

  def license_params
    params.require(:setup_broker).permit( licenses_attributes:[:license_type,:license_number,:license_image, :expiration_date, :id])
  end


end

app/helpers/setup_broker_helper.rb
module SetupBrokerHelper
end

app/views/setup_brokers/_basic_info_1.html.erb
<%provide :title, "|Register Page 1"%>
<h1>Your Background Information (1 of 8)</h1>
<div style="width:60%;text-align:left;padding-top:10px;">
  <%= form_for :broker, :url=> setup_broker_path(@broker), :html => { :method => :put} do|f|%>
  <% if @broker.uid%>
    <%=hidden_field_tag :signup_provider_bool, true%>
    <p><%=f.label "Username"%><%=asterisk_html%></p>
    <p><%=f.text_field :username,{:class=>'form-control'}%></p>
    <%if @broker.password_digest%>
    <div class="alert alert-success" role="alert">
      Password has already been set. 
    </div>
    <%end%>
    <p><%=f.label "Password"%><%=asterisk_html%></p>
    <p><%=f.password_field :password,{:class=>'form-control',title: Order::STRINGS[0]}%></p>
    <p><%= f.label "Password Confirmation" %><%=asterisk_html%></p>
    <p><%= f.password_field :password_confirmation,{:class=>'form-control'} %></p>
  <%end%>
  <p><%=f.label "Email"%><%=asterisk_html%></p>
  <p><%=f.text_field :email,{:class=>'form-control'}%></p>
  <p><%=f.submit 'send validation code', name: "send_validation", class:"btn btn-primary"%></p>
  <%unless @broker.email && (@broker.email_authen==true)%>
  <p><%=f.label "Validation Code"%></p>
  <p><%=f.text_field :validation_code,{:class=>'form-control'}%>    
  </p>   
  <p><%=f.submit "validate email", name:"validate_email", class:"btn btn-primary"%></p>
  <%else @broker.email && (@broker.email_authen==true)%>
  <div class="alert alert-success" role="alert">
    Email address is successfully validated.  
  </div>
  <%end%>
  <p><%=f.label "First Name"%><%=asterisk_html%></p>
  <p><%=f.text_field :first_name,{:class=>'form-control'}%></p>
  <p><%=f.label "Last Name"%><%=asterisk_html%></p>
  <p><%=f.text_field :last_name,{:class=>'form-control'}%></p>
  <p><%=f.label "Title"%><%=asterisk_html%></p>
  <p><%=f.text_field :title,{:class=>'form-control'}%></p>
  <p><%=f.label "Company Name"%><%=asterisk_html%></p>
  <p><%=f.text_field :company_name,{:class=>'form-control'}%></p>
  <p><%=f.label "Company Location"%><%=asterisk_html%></p>
  <p><%=f.text_area :company_location,{:class=>'form-control'}%></p>
  <%=f.submit "Next",name:"next_from_pg1", :class=>"btn btn-lg btn-success", style:"width:100%;"%>
<%end%>
</div>

app/views/setup_brokers/_financial_story_7.html.erb
<%provide :title, "|Register Page 7"%>
<h1>Your Financial Story (7 of 8)</h1>
<div style="width:85%;text-align:left;" class="financial_story_7">
  <div class="panel panel-danger">
    <div class="panel-heading" style="font-size:1.4em;">
      <div style="padding:10px;">
      Please read the instruction below carefully before starting on your financial story:
      </div>
    </div>
    <div class="panel-body">
      <p>Please write a story about how you helped your client in a financial category and vehiicle. <b>You should keep the name anonymous</b>.</p> 
      <p>An example could be that I helped my client to get a life insurance to help with his retirement. In this case, the category is "Retirement" and vehicle is "Life Insurance".</p>
      <p> A good story should include the following points:</p>
      <ul>
        <li>What's your client's financial need?</li>
        <li>What vehicle did you recommend to your client in response to that need?</li>
        <li>How did your service benefit and change the life of your client?</li>
      </ul>
      <p>RichRly does not check content of your financial story- We trust that you will provide good story for our community.</p><br>
    </div>
  </div>
 
  <%= form_for @broker, :url => setup_broker_path(@broker), :html => { :method => :put} do|f|%>

  <%=f.fields_for :financial_stories do |builder|%>
    <table width="100%">
      <tr>
        <td><b>Financial Category</b><%=asterisk_html%></td>
        <td>
          <%=builder.select :financial_category, Order::FINANCIAL_CATEGORIES, {prompt:"Please Select Category"},{:class=>"form-control"}%>
        </td>
      </tr>
      <tr class="blank_row"></tr>
      <tr>
        <td><b>Financial Vehicle</b><%=asterisk_html%></td>
        <td>
          <%=builder.select :product_id, Product.all.collect {|p| [ p.name, p.id ] }, {prompt:"Please Select Vehicle"},{:class=>"form-control"}%>
        </td>
      </tr>
      <tr class="blank_row"></tr>
      <tr>
        <td><b>Story Title</b><%=asterisk_html%></td>
        <td>
          <%=builder.text_field :title,{:class=>"form-control"}%>
        </td>
      </tr>
      <tr class="blank_row"></tr>
      <tr>
        <td colspan=2>
          <b> Enter your story below</b><%=asterisk_html%><br>
          <%=builder.text_area :description, {rows:"25", class:"form-control"}%>
        </td>
      </tr>
    </table>
  <%end%>
  <table width="100%">
    <tr class="blank_row"></tr>
    <tr>
      <td width="48%"><%=f.submit "Previous", name:"back", :class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
      <td width="4%"></td>
      <td width="48%"><%=f.submit "Next",name:"next",:class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
    </tr>
  </table>
<%end%>
</div>

app/views/setup_brokers/_id_2.html.erb
<%provide :title, "|Register Page 2"%>
<h1>Upload Your ID (2 of 8)</h1>

<div style="width:85%;text-align:left;padding-top:10px;">
  <%= form_for :broker, :url=> setup_broker_path(@broker), :html => { :method => :put} do|f|%>
 
  <p style="font-size:1.2em;"> RichRly only accepts your <span style="text-decoration:underline;">State Driver License</span> as a valid form of ID.</p>
  <p><%=f.label "Driver License Upload"%><%=asterisk_html%></p>
  <p><i>Only accepts (.jpg .jpeg .gif .png .pdf) file.</i></p>
  <%=f.hidden_field :id_image%>
  <p><%=f.file_field :id_image, class:"form-control"%></p> 
    <% if (!@broker.id_image.file.blank?) && !@broker.errors.any?%>
    <b>Uploaded:</b>
    <%= link_to "View License", download_driver_license_path(@broker)%>
    <div style="float:right;">
      <%=link_to "remove", remove_id_path(@broker)%>
    </div>
    <%else%>
      
      <%=f.submit "Upload", name:"upload_id", :class=>"btn btn-lg btn-default"%>
    <%end%>
  <%end%><br><br>
  <%= form_for :broker, :url=> setup_broker_path(@broker), :html => { :method => :put} do|f|%>
  <%=f.hidden_field :id_image%>
  <table width="100%">
    <tr>
      <td width="48%"><%=f.submit "Previous", name:"back", :class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
      <td width="4%"></td>
      <td width="48%"><%=f.submit "Next",name:"next",:class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
    </tr>
  </table>
  <%end%>
</div>

app/views/setup_brokers/_license_3.html.erb
<%provide :title, "|Register Page 3"%>
<h1>Select Your Licenses (3 of 8)</h1>
<div style="width:85%;text-align:left;padding-top:10px;">
  <%= form_for :broker, :url => setup_broker_path(@broker), :html => { :method => :put} do|f|%>
    <%= hidden_field_tag "broker[license_type][]", nil %>
    <% licenses=Order::LICENSE_TYPES.to_h.keys%>
    <table width="100%" id="license_table">

    <% for license in licenses%>
      <tr>
        <td width="10%"><%=f.check_box("license_type", {:multiple => true, size:"25x25"}, license, nil)%></td>
        <td width="25%"><%=license%></td>
        <td width="65%"><%=Order::LICENSE_DESCRIPTION_HASH[license]%></td>
      </tr>
      <tr class="blank_row"></tr>
    <%end%>

    </table>
    <table width="100%">
      <tr>
        <td width="48%"><%=f.submit "Previous", name:"back", :class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
        <td width="4%"></td>
        <td width="48%"><%=f.submit "Next",name:"next_from_pg3",:class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
      </tr>
    </table>
  <%end%>
</div>

app/views/setup_brokers/_license_info_4.html.erb
<%provide :title, "|Register Page 4"%>
<h1>Edit Your Licenses (4 of 8)</h1>
<div style="width:85%;text-align:left;">
  <div style="width:100%;" class="alert alert-info error-message">
    <p>Please note the following:</p>
    <ul>
      <li>To remove or add licenses go to the previous page to check or uncheck license types.</li>
      <li>Only licenses registered in New York state will be accepted at this moment.</li>
    </ul>
  </div>
 
  <% @broker.license_type.each do |l|%>
    <%@licenses.each do |t|%>
      <%if t.license_type==l%>
        <%@license=t%>
        <%=render partial: "shared/error_message", locals:{object:@license}%>
        <%= form_for @license do|f|%>
          <table width="100%">
            <tr>
              <td colspan=2>
                <h4><%=f.object.license_type%></h4>
                <%=f.hidden_field :license_type, value:f.object.license_type%>
                <%=hidden_field_tag :broker_id, @broker.id%>
              </td>
            </tr>
            <tr>
              <td width="40%"><%= f.label "License Number" %><%=asterisk_html%></td>
              <td width="60%"><%= f.text_field :license_number,{class:'form-control'} %></td>
            </tr>
            <tr class="blank_row"></tr>
            <tr>
              <td><%= f.label "Expiration Date" %><%=asterisk_html%></td>

              <td><%= f.date_select :expiration_date,{start_year:Date.current.year, end_year:2020,order: [:day, :month, :year]}, {style:"width:32%;"} %></td>
            </tr>
            <tr class="blank_row"></tr>
            <tr>
              <td><%=f.label "State"%></td>
              <td><%=f.hidden_field :state, value:"New York"%></td>
            </tr>
            <tr class="blank_row"></tr>
            <tr>
              <td><%= f.label "Upload License" %><%=asterisk_html%></td>
              <td><%= f.hidden_field :license_image%>
                <%= f.file_field :license_image, {class:'form-control'} %></td>
            </tr>
            <tr class="blank_row"></tr>
            <% if f.object.license_image.file && f.object.license_image.file.filename && !f.object.errors.any?%>
            <tr>
              <td>
                <b>File Uploaded:</b>
                <%= link_to "View License", download_broker_license_path(f.object.id)%>
              </td>
              <td>
                <%= link_to "remove", license_path(id:f.object.id,broker_id:@broker.id,registration:true),method: :delete%>
              </td>
            </tr>
            <%else%>
            <tr>
              <td><%=f.submit "Upload", name:"registration", :class=>"btn btn-primary"%></td>
              <td></td>
            </tr>
            <%end%>
            <tr class="blank_row"></tr>
          </table>
        <%end%>
      <%end%>
    <%end%>
    
  <%end%>
  <%= form_for :broker, :url=> setup_broker_path(@broker), :html => { :method => :put} do|f|%>
    <%=f.hidden_field :id_image%>
    <table width="100%">
      <tr>
        <td width="48%"><%=f.submit "Previous", name:"back", :class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
        <td width="4%"></td>
        <td width="48%"><%=f.submit "Next",name:"next_from_pg4",:class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
      </tr>
    </table>
  <%end%>
</div>

app/views/setup_brokers/_statement_6.html.erb
<%provide :title, "|Register Page 6"%>
<h1>Your Skills and Introduction (6 of 8)</h1>
<div class="alert alert-info">
  <p>The following two fields are not required (You may skip this page if you want).</p>
</div>
<div align="left" style="width:85%;padding-top:10px;">
<%= form_for :broker, :url => setup_broker_path(@broker), :html => { :method => :put} do|f|%>

  <h4>Enter Your Skills and Specialty</h4>(<i>separated by comma</i>)<br>
  <%=f.text_area :skills,{rows:"4",:class=>'form-control'}%>
  <h4>Enter a brief statement about yourself regarding your skills</h4>(<i>150 character max</i>)<br>
<%=f.text_area :ad_statement,{rows:"7",:class=>'form-control'}%><br>
  <table width="100%">
    <tr class="blank_row"></tr>
    <tr>
      <td width="48%"><%=f.submit "Previous", name:"back", :class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
      <td width="4%"></td>
      <td width="48%"><%=f.submit "Next",name:"next",:class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
    </tr>
  </table>

<%end%>
</div>

app/views/setup_brokers/_term_of_use_8.html.erb
<%provide :title, "|Register Page 8"%>
<h1>Term of Condition (8 of 8)</h1>
<div style="text-align:left;width:85%;">
<h3>Please read the following Term of Condition:</h3>
  <div style="height:300px;overflow:auto;border:ridge 1px;">
    <%=render "term_of_use_text"%>
  </div><br>
  <%= form_for :broker, :url => setup_broker_path(@broker), :html => { :method => :put,id:"submit_broker_registration"} do|f|%>
  
  <div class="alert alert-info" role="alert">
    <p>By checking "Term of Use" I agree that I have read and accepted the <%=content_tag(:a,"User Agreement",href:"#User Agreement")%> and <%=content_tag(:a,"Privacy Policy",href:"#Privacy Policy")%>.</p>
    
  </div>
  <div style="float:left;width:10%;"><%=f.check_box :check_term_of_use%></div>
  <div style="overflow:auto;width:90%;">I agree with the term of use.</div>
  <table width="100%" style="text-align:left;">
    <tr class="blank_row"></tr>
    <tr>
      <td width="48%"><%=f.submit "Previous", name:"back", :class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
      <td width="4%"></td>
      <td width="48%"><%=f.submit "Submit",name:"submit",:class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
    </tr>
  </table>
  <div id="broker_register_dialog">
    <p>Are you sure you want to submit?</p>
    <p>Please note that your submission will take 1-3 days to process.</p>
  </div>
<%end%>
</div>

app/views/setup_brokers/_vehicle_5.html.erb
<%provide :title, "|Register Page 5"%>
<h1>Select Your Financial Vehicle (5 of 8)</h1>
<div style="width:85%;text-align:left;">
<%= form_for :broker, :url => setup_broker_path(@broker), :html => { :method => :put} do|f|%>
<%= hidden_field_tag "broker[product_ids][]", nil %>
  <%Order::FINANCIAL_CATEGORIES_HASH.each do |type, category|%>

    <table width="100%">
      <tr>
        <td colspan=4><h3><%=category%></h3></td>
      </tr>
      <% Product.where(vehicle_type:type).each_with_index do |p,index|%>
        <% if index%2 ==0%>
          <tr>
            <td width="10%"><%=f.check_box("product_ids", {:multiple => true, size:"25x25"}, p.id, nil)%></td>
            <td width="40%"><%=p.name%></td>
        <%else%>
            <td width="10%"><%=f.check_box("product_ids", {:multiple => true, size:"25x25"}, p.id, nil)%></td>
            <td width="40%"><%=p.name%></td>
          </tr>
        <%end%>
      <%end%>
    </table>
  <%end%>
  <table width="100%">
    <tr class="blank_row"></tr>
    <tr>
      <td width="48%"><%=f.submit "Previous", name:"back", :class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
      <td width="4%"></td>
      <td width="48%"><%=f.submit "Next",name:"next",:class=>"btn btn-lg btn-success", style:"width:100%;"%></td>
    </tr>
  </table>
<%end%>
</div>

app/views/setup_brokers/edit.html.erb
<div style="width:85%;">
  <%if @validate_email_error%>
    <%@broker.addition_error_msg=" when sending validation code."%>
  <%end%>
  <%=render partial:"shared/error_message", locals:{object:@broker}%>
</div>
<%=render "setup_brokers/#{@broker.current_field}"%>
<% content_for :right do%>
<div style="padding-top:20px;">
  <div class="alert alert-info" style="width:100%;text-align:left;">
    <p style="font-size:1.5em;line-height:150%;">This is your application. After you submit your application, we will review your licenses attachments. You are free to login and use the website after submission. But until we approve your application, your profile, financial stories won't be shown to the public. For more information about criteria for successful registration, please refer to <span style="text-decoration:underline;"><%=link_to "Broker Registration Criteria", broker_registration_criteria_path, :target => '_blank'%></span>.</p>
  </div>
</div>
<%end%>

app/views/setup_brokers/new.html.erb
<%= form_for @broker do|f|%>
  <table width="60%">

    <%= f.fields_for :licenses do |builder| %>
      <% #@broker.license_type.each do |l|%>
      <% l="test"%>
        <tr>
          <td colspan=2>
            <%=l%><%=f.hidden_field :license_type, value: Order::LICENSE_TYPES.to_h[l]%>
          </td>
        </tr>
        <tr>
          <td width="40%"><%= builder.label "License Number" %></td>
          <td width="60%"><%= builder.text_field :license_number,{class:'form-control'} %></td>
        </tr>
        <tr class="blank_row"></tr>
        <tr>
          <td><%= builder.label "Upload License" %></td>
          <td><%= builder.file_field :picture, {class:'form-control'} %></td>
        </tr>
        <tr class="blank_row"></tr>
      <%#end%>
    <%end%>
  </table>
  <%=f.submit "Previous", name:"back", :class=>"btn btn-lg btn-default"%>
  <%=f.submit "Next",name:"next", :class=>"btn btn-lg btn-default"%>
<%end%>